### ISSUE TITLE
Failed to migrate article

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-concierge#5]
_It was easy to recover from this issue. Providing the link to the original article made it trivial to manually recreate the article and insert it in the correct point in the tour. I am submitting it as in issue in case there is a straight forward remediation for what caused it to failure initially._

### Issue:
Article failed to migrate

### Actions to reproduce:
On VM test environment, migrate '1 Dollar, China, 1923'
'Tour Stop 2' (Step 4 of 29) shows the text
`Failed to migrate article from 'https://3d.si.edu/play/sidebar/p1b-1565825132268-1566320819053-0'`

<img width="1680" alt="Screen Shot 2019-12-17 at 2 54 03 PM" src="https://user-images.githubusercontent.com/49207360/71037268-61e5a780-20ed-11ea-9bb6-2d37771c51c7.png">

**Comment by framefactory** [comment]
Article migration might fail in rare cases due to a number of reasons. It is one of the most involved steps in the migration process, because articles need to be fetched, their content parsed, images retrieved and converted and then everything gets reassembled. If an article has a formatting issue or a link to an image is broken, article conversion fails. As you already figured out, the displayed link helps in retrieving the article manually.
