### ISSUE TITLE
Migrated articles attached to scene, model, and some times both.

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-concierge#6]
_This might not be an issue, but you don't know till you ask :) Largest concern is understanding if there is a way to designate an article that opens by default in the article viewer._

### Issue:
Migrated tour articles attached to both the scene and part (The default article only attaches to the scene)

Also multiple links in the Articles 'Task' pane are created for articles used in multiple tour stops, but these links point to the same html article

### Actions to reproduce:
On VM test environment, migrate '1 Dollar, China, 1837' or '1 Dollar, China, 1923'

View article list in 'Task' pane of Voyager Story while in 'Articles' tab

<img width="1680" alt="Screen Shot 2019-12-17 at 4 59 12 PM" src="https://user-images.githubusercontent.com/49207360/71038348-a4a87f00-20ef-11ea-9951-260c22f4e0ac.png">

<img width="1680" alt="Screen Shot 2019-12-17 at 4 59 07 PM" src="https://user-images.githubusercontent.com/49207360/71038333-9bb7ad80-20ef-11ea-8555-b2fa9aea3253.png">

<img width="1680" alt="Screen Shot 2019-12-17 at 5 09 57 PM" src="https://user-images.githubusercontent.com/49207360/71038566-1ed90380-20f0-11ea-8096-c4e9a864248e.png">

<img width="1680" alt="Screen Shot 2019-12-17 at 5 10 00 PM" src="https://user-images.githubusercontent.com/49207360/71038561-1d0f4000-20f0-11ea-89fb-760ff8f3c497.png">

**Comment by framefactory** [comment]
This is intended behavior. Because a Play scene attaches articles individually to annotations and tours, some rearrangement is necessary. It works as follows:
- All annotations are attached to the first model of the scene
- Articles referenced through annotations are also attached to the first model
- Articles referenced during a tour and the default article are attached to the scene

If you want to set a (different) default article that shows after loading, just bring up that article in the reader, then either close the reader or keep it open, depending whether you want the user to see the article immediately or after clicking the reader button. Then save the scene.

Generally, the scene always opens in the exact same state as it is saved.
